import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>sh1ggy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <main>
          
          <h1>
            Welcome to sh1ggy Web
          </h1>
          <p>
            Tyrone Nolasco's {' '}
            <code>code_portfolio.tsx</code>
          </p>

        </main>
        <footer>
          <small><a href="https://github.com/sh1ggy">sh1ggy</a> • <a href="https://github.com/sh1ggy/sh1ggy-web">Source Code</a></small>
        </footer>
      </body>
    </>
  )
}

export default Home
