import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { MatrixRain } from '../components/matrix'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>sh1ggy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MatrixRain />
      <nav style={{padding:'50px'}}>
        <ul>
          <li>shiggy-dev</li>
        </ul>
        <ul>
          <li>
            <Link href="/blog">
              <a>Blog</a>
            </Link>
          </li>
          <li>
            <Link href="/tools">
              <a>Tools</a>
            </Link>
          </li>
        </ul>
      </nav>
      <body>
        <main>
          <hgroup>
            <h1>Welcome to {' '} <code>sh1ggy-web</code></h1>
            <h3>Tyrone Nolasco's code portfolio</h3>
          </hgroup>
          <p>This is a general overview on the key parts of my personal programming journey as well 
          as a fun way to play around with website development and show off a bit of my personality.
          </p>
        </main>
        <footer>
          <small><a href="https://github.com/sh1ggy">sh1ggy</a> • <a href="https://github.com/sh1ggy/sh1ggy-web">Source Code</a></small>
        </footer>
      </body>
    </>
  )
}

export default Home
